const D={hero_eyebrow:"The House Always Streams",hero_name:"ADGstream",hero_tag:"Streamer Casino Card Magic",hero_btn_watch:"Regarder sur Twitch",about_title:"La magie des cartes, en live",about_p1:"Bienvenue sur ma chaine.",about_p2:"Je stream du poker, du blackjack et de la magie !",stat1_num:"263",stat1_lbl:"Followers",stat2_num:"5x",stat2_lbl:"Par semaine",stat3_num:"4 mois",stat3_lbl:"En stream",schedule_week:"--",schedule_days:[{day:"DIM",num:"--",act:"",time:"",off:true},{day:"LUN",num:"--",act:"Poker Night",time:"20h-23h",off:false},{day:"MAR",num:"--",act:"Casino Night",time:"21h-00h",off:false},{day:"MER",num:"--",act:"",time:"",off:true},{day:"JEU",num:"--",act:"Card Magic",time:"20h-22h",off:false},{day:"VEN",num:"--",act:"",time:"",off:true},{day:"SAM",num:"--",act:"Weekend Special",time:"19h-23h",off:false}],clips:[],clip_categories:{},social_links:{twitch:"https://twitch.tv/adgstream",discord:"https://discord.gg/kcRtUEnb",tiktok:"https://tiktok.com/@adgstream",kofi:"https://ko-fi.com/adgstream"},footer_tag:"La table est toujours ouverte",twitch_channel:"adgstream",discord_invite:"kcRtUEnb",discord_guild_id:"",characters:[],story:{chapter:"Chapitre 1",date:"--",body:"La salle etait plongee dans une semi-obscurite violette...",teaser:"La suite au prochain stream..."},tiktok_posts:[],instagram_posts:[],blackjack:{free_rounds:3,message:"Soutenez le stream pour continuer !",enabled:true},facolix:{show_on_home:true,about:"Facolix est mon co-streamer !",schedule_days:[],social_links:{twitch:"https://www.twitch.tv/facolix",discord:"https://discord.gg/kcRtUEnb"}}};
async function getKV(){const{createClient}=await import('@vercel/kv');return createClient({url:process.env.STORAGE_URL||process.env.KV_REST_API_URL,token:process.env.STORAGE_TOKEN||process.env.KV_REST_API_TOKEN})}
async function isAuthed(req){const c=req.headers['cookie']||'';const m=c.match(/adg_session=([^;]+)/);if(!m)return false;try{const kv=await getKV();return !!(await kv.get('adgstream:session:'+m[1]))}catch(e){return false}}
export default async function handler(req,res){
  res.setHeader('Access-Control-Allow-Origin','*');
  res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers','Content-Type');
  if(req.method==='OPTIONS')return res.status(204).end();
  if(req.method==='GET'){try{const kv=await getKV();const s=await kv.get('adgstream:content');return res.status(200).json(s?{...D,...s}:D)}catch(e){return res.status(200).json(D)}}
  if(req.method==='POST'){if(!(await isAuthed(req)))return res.status(401).json({error:'Non autorise'});try{const kv=await getKV();const e=await kv.get('adgstream:content')||D;await kv.set('adgstream:content',{...e,...req.body});return res.status(200).json({ok:true})}catch(e){return res.status(500).json({error:e.message})}}
  res.status(405).json({error:'Method not allowed'});
}